# Generated by Django 3.0.3 on 2020-04-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_explain',
            field=models.CharField(default='', max_length=200),
        ),
    ]
