# Generated by Django 3.0.3 on 2020-04-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_filter_filter_explain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
