# Generated by Django 3.0.3 on 2020-04-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_src',
            field=models.ImageField(upload_to='.'),
        ),
    ]
