# Generated by Django 3.0.3 on 2020-04-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0006_auto_20200406_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_src',
            field=models.ImageField(upload_to='./upload'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filters.Filter')),
            ],
        ),
    ]
