# Generated by Django 3.0.3 on 2020-04-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0008_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
