# Generated by Django 3.0.3 on 2020-04-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0010_auto_20200415_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
