# Generated by Django 3.0.3 on 2020-04-24 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filters.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filters', '0011_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_src',
            field=models.ImageField(upload_to=filters.models.get_upload_to),
        ),
    ]
