# Generated by Django 3.0.3 on 2020-04-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0014_auto_20200424_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='username',
            new_name='user',
        ),
    ]
