# Generated by Django 3.0.5 on 2020-05-08 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0016_auto_20200425_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='image',
            name='img_opt_name',
            field=models.CharField(default='img_opt', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='img_src_name',
            field=models.CharField(default='img_src', max_length=100),
        ),
    ]
